name: anilist_client
description: "This is a demo anilist client project."
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: 1.2.1
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/png/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/comfortaa/comfortaa_variable.ttf
          style: normal
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/raleway_variable.ttf
          style: normal
        - asset: assets/fonts/raleway/raleway_italic_variable.ttf
          style: italic
    - family: Font Awesome
      fonts:
        - asset: assets/icons/fontawesome.ttf